CREATE TABLE factor_repo_financial_indicator AS
SELECT 
    ts_code,
    ann_date,
    end_date,
    assets_to_eqt,
    bps,
    ca_to_assets,
    cfps,
    current_ratio,
    currentdebt_to_debt,
    debt_to_assets,
    dtprofit_to_profit,
    ebitda_to_debt,
    ebit_of_gr,
    ebit_to_interest,
    q_eps,
    diluted2_eps,
    expense_of_sales,
    debt_to_eqt,
    grossprofit_margin,
    inv_turn,
    netprofit_margin,
    ocf_to_interestdebt,
    ocf_to_opincome,
    op_of_gr,
    q_sales_yoy,
    profit_to_gr,
    quick_ratio,
    roa,
    roe,
    roic,
    tax_to_ebt,
    turn_days,
    equity_yoy,
    tr_yoy,
    basic_eps_yoy,
    cfps_yoy,
    op_yoy,
    netprofit_yoy
FROM repo_financial_indicator
WHERE ts_code IN (SELECT ts_code FROM ts_code);

